// react-test/demo/Post.js
import React from "react";
import Profile from "./Profile";
import Comment from "./Comment";

class Post extends React.Component {
  render() {
    const { post, comments, postLoading, commentsLoading } = this.props;

    return (
      <article className="post">
        {postLoading ? (
          <div className="post__photo">
            <div>Loading</div>
          </div>
        ) : (
          <div className="post__photo">
            <img
              className="post__img"
              src={post.images.standard_resolution.url}
            />
          </div>
        )}
        <div className="post__content">
          {commentsLoading ? (
            <div>Loading</div>
          ) : (
              <div>
                   <Profile
              profile_picture={post.user.profile_picture}
              username={post.user.username}
            />
            <div className="comments">
              {comments.map(comment => (
                <Comment text={comment.text} from={comment.from.username} />
              ))}
            </div>
            </div>
          )}
        </div>
      </article>
    );
  }
}

export default Post;

// react-test/output/post.component.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "post",
  templateUrl: "./post.component.html",
  styleUrls: ["./post.styles.scss"]
})
export class Post {
  @Input()
  postLoading;
  @Input()
  post;
  @Input()
  commentsLoading;
  @Input()
  comments;
}
<article class="post">
  <ng-container *ngIf="postLoading; then tmpl_PostLoading; else tmpl_NotPostLoading"></ng-container>
  <ng-template #tmpl_PostLoading>
    <div class="post__photo">
      <div>Loading</div>
    </div>
  </ng-template>
  <ng-template #tmpl_NotPostLoading>
    <div class="post__photo">
      <img class="post__img" [src]="post.images.standard_resolution.url">
    </div>
  </ng-template>
  <div class="post__content">
    <ng-container *ngIf="commentsLoading; then tmpl_CommentsLoading; else tmpl_NotCommentsLoading"></ng-container>
    <ng-template #tmpl_CommentsLoading>
      <div>Loading</div>
    </ng-template>
    <ng-template #tmpl_NotCommentsLoading>
      <div>
        <profile [profile_picture]="post.user.profile_picture" [username]="post.user.username"></profile>
        <div class="comments">
          <comment *ngFor="let comment of comments" [text]="comment.text" [from]="comment.from.username"></comment>
        </div>
      </div>
    </ng-template>
  </div>
</article>
