// react-test/demo/Profile.js
import React from "react";

class Profile extends React.Component {
  render() {
    const { profile_picture, username } = this.props;

    return (
      <header className="user">
        <span className="avatar">
          <img className="avatar__img" src={profile_picture} />
        </span>

        <div className="user__info">
          <div className="name">
            {username}
            <a className="link" href="#">
              Follow
            </a>
          </div>
          <a className="location" href="#">
            Amsterdam
          </a>
        </div>
      </header>
    );
  }
}

export default Profile;

// react-test/output/profile.component.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "profile",
  templateUrl: "./profile.component.html",
  styleUrls: ["./profile.styles.scss"]
})
export class Profile {
  @Input()
  profile_picture;
  @Input()
  username;
}
<header class="user">
  <span class="avatar">
          <img class="avatar__img" [src]="profile_picture">
        </span>

  <div class="user__info">
    <div class="name">
      {{username}}
      <a class="link" class="#">
        Follow
      </a>
    </div>
    <a class="location" class="#">
      Amsterdam
    </a>
  </div>
</header>
