// react-test/output/comment.component.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "comment",
  templateUrl: "./comment.component.html",
  styleUrls: ["./comment.styles.scss"]
})
export class Comment {
  @Input()
  from;
  @Input()
  text;
}
<div class="comment">
  <h3 class="comment__author">{{from}}</h3>
  <span class="comment__text">{{text}}</span>
</div>

// react-test/demo/Comment.js
import React from 'react'

class Comment extends React.Component {
    render() {
        const {from,text} = this.props;

        return (
            <div class="comment">
                <h3 class="comment__author">{from}</h3>
                <span class="comment__text">{text}</span>
            </div>
        )
    }
}

export default Comment;
